apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: backend-api
  name: backend-api
  namespace: devops
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend-api
  strategy: 
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: backend-api
    spec:
      imagePullSecrets:
        - name: ecr-secret
      containers:
      - image: 211125410061.dkr.ecr.us-west-2.amazonaws.com/backend:1
        name: backend
        env:
        - name: MONGO_USERNAME
          valueFrom:
            secretKeyRef:
              name: mongo-secret       # Kubernetes Secret name
              key: MONGO_INITDB_ROOT_USERNAME
        - name: MONGO_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mongo-secret
              key: MONGO_INITDB_ROOT_PASSWORD
        - name: MOGO_HOST
          value: mongo-svc
        resources: {}
status: {}
