apiVersion: v1
kind: Service
metadata:
  labels:
    app: backend-api
  name: backend-api
  namespace: devops
spec:
  ports:
  - port: 3500
    protocol: TCP
    targetPort: 3500
  selector:
    app: backend-api
status:
  loadBalancer: {}
