apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-volume
  namespace: devops
  labels:
    type: local
spec:
  volumeMode: Filesystem
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"