apiVersion: v1
kind: Service
metadata:
  labels:
    app: mongodb
  name: mongo-svc
  namespace: devops
spec:
  ports:
  - port: 27017
    protocol: TCP
    targetPort: 27017
  selector:
    app: mongodb
status:
  loadBalancer: {}
