apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: frontend
  name: frontend
  namespace: devops
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
  strategy: 
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: frontend
    spec:
      imagePullSecrets:
        - name: ecr-secret
      containers:
      - image: 211125410061.dkr.ecr.us-west-2.amazonaws.com/frontend:6
        name: frontend
        ports:
        - containerPort: 3000
        env:
          - name: REACT_APP_BACKEND_URL
            value: "http://vaibhavmdevops.live/api/tasks"
        resources: {}
status: {}
